spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native
server:
  port: 8888
security:
    user:
      name: root
      password: root$123
